name: build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Lint
        run: |
          npm install -g gulp
          npm install
          gulp lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16, 18]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Test
        run: |
          npm install -g gulp
          npm install
          gulp mocha
